### ISSUE TITLE
Publish django-tex in pip

### ISSUE THREAD

**Issue by flavoi** [weinbusch/django-tex#1]
Hi man,
your work is much appreciated.
Could you please make this package available on pip?
It would greatly benefit automatic deploys of python projects.

Thanks!
Flavio

**Comment by weinbusch** [comment]
Thanks for your interest, Flavio.

I have uploaded the package on test.pypi.org, from where it can be installed via pip. I do not want to upload it to the proper pypi repsitory, as the code will probably still change a lot and I cannot guarantee future support.
