### ISSUE TITLE
Problem with pdflatex

### ISSUE THREAD

**Issue by asingh1994** [weinbusch/django-tex#11]
Hello Martin,
I have a problem with PDF Latex. Whenever I retrieve the website, ,,_The command "pdflatex" either misspells or could not be found_" appears. Can you help me with that?

Hallo Martin,
immer wenn ich mein View abrufe, der die PDF erstellen soll, erscheint der Fehler: _Der Befehl "pdflatex" ist entweder falsch geschrieben oder konnte nicht gefunden werden_. Kannst du mir damit eventuell helfen?

Thank you very much
Avi

**Comment by weinbusch** [comment]
Hello Avi,

the pdflatex binary might not be installed on your system or the process running django has no access to it. Can you check by opening a command prompt on the machine running django and type in "pdflatex"?

Regards
m

**Comment by weinbusch** [comment]
I'll close this for now ...

**Comment by asingh1994** [comment]
Thank you very much for your support. I tried it, but it still doesn’t work. But I think i can handle it with your tips. You can close it.
Thanks a lot
