### ISSUE TITLE
No output generated if temporary folder is on different drive

### ISSUE THREAD

**Issue by rinnegger** [weinbusch/django-tex#12]
In run_tex() there is an issue with the latex_command if the temporary folder is on a different drive than the current working directory (at least on windows). It needs the a "drive change" before the cd.
A possible soluton could be
```
        tempdrive = os.path.splitdrive(tempdir)[0]
        latex_command = f'{tempdrive} && cd "{tempdir}" && {latex_interpreter} ' \
                        f'-interaction=batchmode {latex_interpreter_options} {os.path.basename(filename)}'

```

**Comment by weinbusch** [comment]
thanks for pointing this out. Do you have any way to test this? Could you submit a pr and and see if it passes the current tests?

**Comment by rinnegger** [comment]
Sorry, atm I don't have a shareable code... I found out while dev. on a windows machine where my project is located on drive D:\ and the temporary folder is under C:\Users\...

**Comment by weinbusch** [comment]
I'll close this for now. Let me know if you have any further questions.
