### ISSUE TITLE
Strip LaTeX source of \r

### ISSUE THREAD

**Issue by essayen** [weinbusch/django-tex#13]
I am using django-tex to create LaTeX files including content in the lstslisting environment. If run on Windows this leads to the problems that during the creation of the LaTeX source code Windows line endings are used. That results in extra empty lines in the lstlisting environment due to the \r. It would be great to strip the source of \r before writing the tex file. In my local version I added a corrsponding replace in run_tex(), but I do not know if this would be the best place for it.

**Comment by weinbusch** [comment]
Hi there! Can you write a test that reproduces the unwanted behaviour? I think there should be some built-in python way of handling line endings when writing the temporary file, but I'm not sure. It would be easier for me to solve this, if I had a test

**Comment by weinbusch** [comment]
I'll close this for now. Let me know if you have any further questions.
