### ISSUE TITLE
Multi-pass

### ISSUE THREAD

**Issue by gonteroc** [weinbusch/django-tex#14]
For some latex functionality ( table, count pages, ... ) the document need to be processed 2 or more time
For that i done a modification :
In django_tex/core.py
def run_tex(source, multi_pass=1):
    ...
    latex_command = f'cd "{tempdir}" && {latex_interpreter} -interaction=batchmode {latex_interpreter_options} {os.path.basename(filename)}'
    i=0
    while i < multi_pass:
        process = run(latex_command, shell=True, stdout=PIPE, stderr=PIPE)
        i += 1
and
def compile_template_to_pdf(template_name, context, multi_pass=1):
    source = render_template_with_context(template_name, context)
    return run_tex(source, multi_pass)

**Comment by weinbusch** [comment]
This has been discussed before; please take a look at issue #3. I believe, using `latexmk` should be the preferred solution.

**Comment by weinbusch** [comment]
I'll close this for now. Let me know if you have any further questions.
