### ISSUE TITLE
How to insert image which is stroed in bytesIO() buffer?

### ISSUE THREAD

**Issue by jakubradziwon** [weinbusch/django-tex#15]
Hi, I am trying to insert dynamically made qrcode (with qrcode python package). My image is stored in buffer, when I show the buffer in the template I get (in pdf):
`<qrcode.image.pil.PilImage object at 0x7f970c245730>`
but 
`\\includegraphics{{{qr_tel}}}`
renders nothing. Is there easy way to put such images in tex template ?

**Comment by weinbusch** [comment]
`\includegraphics` is a latex command that requires a path to an image file. Passing a python object representing an image, such as a PilImage object, won't work. If you do `\\includegraphics{{{qr_tel}}}` in your template, `jinja` will render the `qr_tel` object by calling its `__str__` or `__repr__` method (I don't exaclty know which one) to produce a string and insert the string into the generated .tex file. The .tex is then passed by `django-tex` to the latex compiler and the latex compile will try to execute the `\includegraphics` command. If the argument to that command is not a valid path to an image file, it will raise an error. 

Solution: Save your image in a file format that the latex compiler can handle (e.g. png for pdflatex) and render the path to your image file in your template. Make sure that the image is saved to a location that is accessible to the process running your django app.

**Comment by jakubradziwon** [comment]
Thanks, I've already implement "save to folder", compile pdf and then delete the image.
