### ISSUE TITLE
provide context on latex-build error

### ISSUE THREAD

**Issue by droundy** [weinbusch/django-tex#16]
It would be lovely if there was some way to give the latex content around the line identified in the error message when latex fails to build the file.  Currently I get a TexError with something like:
```
! Missing $ inserted. <inserted text>  $ l.37  I've inserted a begin-math/end-math symbol since I think you left one out. Proceed, with fingers crossed.
```
but it's a pain to try to figure out what line 37 is in the expanded template.

**Comment by weinbusch** [comment]
Hello there, that is a good idea. Please take a look at the referenced pull request and tell me whether that solves your problem.

**Comment by droundy** [comment]
It sounds like a good solution! (But I've hardly skimmed the code, so don't interpret this as a code review!)
