### ISSUE TITLE
Using arrays in a template

### ISSUE THREAD

**Issue by MosGeo** [weinbusch/django-tex#19]
Is it possible to use arrays In a template, for example, I have an array of strings that I want to insert each in the same page template.

**Comment by MosGeo** [comment]
OK, update: it is actually possible to use jinga syntex in the tex template. Awesome! I can now use for loops and access arrays normally.

**Comment by MosGeo** [comment]
Answered my own question.

**Comment by ramiboutas** [comment]
Hi Mustafa, nice! how did you do it? I am getting one error: _[Errno 2] No such file or directory: '/tmp/tmppnic24vh/texput.pdf'_
I am trying to loop through a list of strings called paragraphs -> paragraphs = ['this is my first paragraph', 'this is my second paragraph']

my tex file looks like this

`\documentclass{article}

\begin{document}

{% for paragraph in paragraphs %}
  {{ paragraph  | linebreaks }}
{% endfor %}

\end{document}`

Thank you very much!
