### ISSUE TITLE
For generating TableOfContents etc. LaTeX needs to run twice

### ISSUE THREAD

**Issue by MaHaArt** [weinbusch/django-tex#20]
Would be nice to have an option to run LaTeX twice in order to generate indices and content tables.

Currently two things prevent the approach:

1. run_tex calls run_tex_in_directory within a temp directory which - along with the auxilliary files to generated ToC - gets deleted after each run.
2.  run_tex_in_directory opens the generated tex file with the "x" option. Thus an error would be raised if TeX file is already existing from previous run.

**Comment by weinbusch** [comment]
Take a look at issue #3. For now, the best option is to use `latexmk` for compiling your .tex source files. Pull request #4 explains how this is done.
