### ISSUE TITLE
Generating Table of Contents

### ISSUE THREAD

**Issue by alexanderjulmer** [weinbusch/django-tex#23]
I am using `django-tex` to generate a book and would like to add a table of contents using `\tableofcontents`. Unfortunately, this does not work. I suspect this is because the table is generated by finding headlines in the document which only exist after templating. When using a a latex engine on the command line, the problem can be fixed by running it twice with the first run creating the `*.toc` file and the second run using it to create the template.

Is there a similar strategy for `django-tex`, i.e. generate the `.toc` file separately? I would also like to use this file for splitting up the generated PDF later.

**Comment by weinbusch** [comment]
Hi there, this has been discussed before; please take a look at issue #3. I believe using `latexmk` should be the preferred solution. If this is not sufficient and we have to replicate the functionality of `latexmk` in python, were in for a major pr (parsing the latex log to check whether LaTeX and/or BibTeX need to be called repeatedly).
