### ISSUE TITLE
FileNotFoundError when trying to use lib

### ISSUE THREAD

**Issue by autoantwort** [weinbusch/django-tex#27]
I have the following code to generate a pdf:
```python
for n in data_house:
print(n)
context = {
  'data_house': data_house,
}
PDF = compile_template_to_pdf('monthly_fees.tex', context)
```
and the following latex file:
```latex
\documentclass{letter}

\begin{document}
  \begin{letter}{}
  {% for n in data_house %}
    test
  {% endfor %}
  \end{letter}
\end{document}
```
and only get the error: `[Errno 2] No such file or directory: '/var/folders/2t/jzczznpx033c6tbrdt24ldhw0000gn/T/tmpjcwiboj8/texput.pdf'` Any Idea? 
Stacktrace: https://dpaste.com/5RNAWFEGE

**Comment by weinbusch** [comment]
From the line numbers in your stack trace, it seems you are using an older version of `django-tex`. Try updating it and let me know the resulting error message, if any.

In your `settings.py`, do you set `LATEX_INTERPRETER` and/or `LATEX_INTERPRETER_OPTIONS`?

**Comment by autoantwort** [comment]
Soory for not updating the issue. The "problem" was that `data_house` was an empty list, so that the content of the tex file was only 
```tex
\documentclass{letter}
\begin{document}
  \begin{letter}{}
  \end{letter}
\end{document}
``` 
and it seems to be that for "empty" files no pdf is created.
