### ISSUE TITLE
unable to create pdf file

### ISSUE THREAD

**Issue by theetherGit** [weinbusch/django-tex#28]
i'm setting it up correctly but always getting error related to command cd "" && pdflatex return non-zero exit status 1

**Comment by gkKshitij** [comment]
maybe a little improvement in readme could help, cause its the same thing everywhere.

**Comment by weinbusch** [comment]
I need to have more information on your setup/configuration in order to help. Can you provide a minimal code example? Did you try updating django-tex?

**Comment by gkKshitij** [comment]
Configuration:
anaconda full individual installation
python v3.9.6
django 3.2.6
pdflatex==0.1.3
django-tex==1.1.9.post1
latex==0.7.0
also installed the latest available texworks installation
tested only on windows10 with visual studio code

"pdflatex main.tex" was working in cmd, 
os.system("pdflatex main.tex") and also subprocess.check_call was also working in a python script file, 
and also the pdf was compiling in texworks.

I followed all the steps in the readme file accordingly and also configured the urls.py etc and other necessary things.
According to my understanding of the error, it is getting stuck at the temporary directory stage.
I even tested other Django/python modules that help to convert tex to pdf, all are giving the same problem.

So either I am doing something wrong(most probably) or some update messed up the process.

I am just trying to duplicate your process in the readme file with the same main.tex content in the templates folder.
Here is the error code: (also the same displayed on browser)
#####################start
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Not Found: /
[10/Aug/2021 00:22:28] "GET / HTTP/1.1" 404 2561
Internal Server Error: /cv/preview/
Traceback (most recent call last):
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django_tex\core.py", line 29, in run_tex_in_directory
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KASPPRO\\AppData\\Local\\Temp\\Q-DirPortableTemp\\tmpqn319po0\\texput.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "P:\workspace\django\cvg\generator\views.py", line 12, in preview
    kscript()
  File "P:\workspace\django\cvg\generator\views.py", line 29, in kscript
    PDF = compile_template_to_pdf(template_name, context)
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django_tex\core.py", line 44, in compile_template_to_pdf
    return run_tex(source, template_name=template_name)
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django_tex\core.py", line 15, in run_tex
    return run_tex_in_directory(source, tempdir, template_name=template_name)
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django_tex\core.py", line 34, in run_tex_in_directory
    raise called_process_error
  File "P:\compilers\anaconda\envs\cvgenv\lib\site-packages\django_tex\core.py", line 26, in run_tex_in_directory
    run(args, shell=True, stdout=PIPE, stderr=PIPE, check=True)
  File "P:\compilers\anaconda\envs\cvgenv\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd "C:\Users\KASPPRO\AppData\Local\Temp\Q-DirPortableTemp\tmpqn319po0" && pdflatex -interaction=batchmode  texput.tex' returned non-zero exit status 1.
[10/Aug/2021 00:22:34] "GET /cv/preview/ HTTP/1.1" 500 113365
######################end
![views py_-_cvg_-_Visual_Studio_Code_10August21_000846_129](https://user-images.githubusercontent.com/42409384/128762801-930a1613-25f2-485b-b17a-3aef1ae0fbc8.png)

I also have a question, can't we just use os/subprocess in the directory of views.py or templates, what is the need for a temp directory? and does it have any impact on I/Os or processing while hosting on cloud services like AWS?

I am a bit new to coding and even new to Django, please let me know if I am doing anything wrong, and thank you for your quick reply😊 let me know if you need anything else, and sorry in advance if it's anything foolish.

**Comment by gkKshitij** [comment]
hey buddy your code is highly generalized (flexible) and awesome, its like the industry-level code I still dream of writing someday.
But currently as a work around the code below seems to be doing the job for me,
(not sure of the other problem I am gonna face due to this most probably while deploying).
########### code start
def edit(request):
    cwd = os.getcwd() 
    stdir = os.path.join(cwd, "generator\static\generator")#, "test.tex")
    fp = os.path.join(cwd, "generator\static\generator", "test.pdf")
    os.chdir(stdir)
    subprocess.check_call(['pdflatex', '-interaction=nonstopmode', 'test.tex'])
    os.remove("test.aux")
    os.remove("test.log")
    os.chdir(cwd)

    return FileResponse(open(fp, 'rb'), content_type='application/pdf')
    # return HttpResponse(f"{stdir}")
########### end
currently I am just testing what all modules I can make use of, reason for poor code😜
output:
![image](https://user-images.githubusercontent.com/42409384/128815457-a9d39ca2-2ab8-4468-ad0f-07954adbc2a4.png)

**Comment by weinbusch** [comment]
I do not have an immediate solution to your problem. However, I made a commit to the `next` branch, in which I made a small change to the `run_tex_in_directory` function. Could you try that one on your computer? Please also try to run the tests with `python manage.py test` and take look at the test app `python manage.py runserver` to see if they work. 

I am mainly using the temporary directory to clean all files created by latex after the process has finished. I think this is easier and more reliable than cleaning all files by hand using multiple os.remove calls.

**Comment by gkKshitij** [comment]
extremely sorry for the late reply, But cheers it worked for me. It took a (long) while cause I am still learning😜.
I don't know y tests 3 and 4 failed but anyways it is working now. (P.S. still learning to write tests)
I was just learning about deploying on Heroku and it seems like services like heroku don't allow to write in the app directory or any directory once deployed, which means that your module works rather than my shitty workaround as it uses temp directory which is available for everyone. Kudos to you sir and really thanks for the help!
And I hope you can close this issue now✌.

**Comment by ericel** [comment]
Getting the same error above. How did you get it to work @gkKshitij
