### ISSUE TITLE
Filter linebreaks doesn't work for empty lines in TextField = tex-error

### ISSUE THREAD

**Issue by jsmendek** [weinbusch/django-tex#34]
When I have an empty line in a django TextField and I want to render this with the latex_escape-filter, I got a tex-error:
> ! LaTeX Error: There's no line here to end.

**Comment by weinbusch** [comment]
Please provide a minimal example and ideally a test illustrating the desired behaviour

**Comment by jsmendek** [comment]
Okay, no problem.

models.py:
```
from django.db import models 
  
 class TestModel(models.Model):
      text_field = models.TextField(
              verbose_name='Input',
      )
```
Fill in the admin-backend the text_field with

> first line
>
> third line

test.tex:
```
\documentclass{article}

\begin{document}
{{- foo|linebreaks -}}
\end{document}
```

view.py:
```
from django.shortcuts import render
from django_tex.shortcuts import render_to_pdf
from .models import TestModel

def view(request):
    obj = TestModel.objects.first()
    template_name = 'tt/test.tex'
    context = {'foo': obj.text_field }
    return render_to_pdf(request, template_name, context, filename='test.pdf')

```

I get this tex-error:

> ! LaTeX Error: There's no line here to end.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.7 T
> 
> 2 
> 3 \begin{document}First Line
> 4 \\
> 5 
> 6 \\
> 7 Third Line\end{document}

I tried {{- foo|latex_escape|linebreaks -}}, but is has the same error. In the TextField the string is `First Line\r\n\r\nThird Line` and not `First Line\n\nThird Line`!

**Comment by weinbusch** [comment]
Your `test_text` string contains an empty line. For Latex, an empty line indicates a new paragraph. However, you are not allowed to have multiple paragraphs in a `\section`. Your template produces the following command in your .tex file (see the log):

```
\section{first line

thirdline}
```

Latex cannot compile this because of the empty line.

`latex_escape` does not remove the empty line. You have to do it, before passing the string to the template, e.g. by `test_text.replace("\n", " ")`.

**Comment by jsmendek** [comment]
Thanks for your answer. You are right. In a \section it is not correct. I check my code again and I correct my example. There is indeed another error. I change my codeexample.
