### ISSUE TITLE
django-tex on the default pypi index

### ISSUE THREAD

**Issue by gegenschall** [weinbusch/django-tex#6]
Hi,

thanks for your work on this, greatly appreciated!

I'm using pipenv to manage my packages and currently cannot install django-tex because I end up with the Django version from the test PyPI (see: https://github.com/pypa/pipenv/issues/3444). 
Would you consider pushing the package to the main PyPI index?

Thanks in advance!

**Comment by weinbusch** [comment]
Done. I think ... please tell me if anything doesn't work.

**Comment by gegenschall** [comment]
Awesome, thanks so much! :)
