### ISSUE TITLE
Django requirement pinned to 1.11

### ISSUE THREAD

**Issue by gegenschall** [weinbusch/django-tex#7]
Hey Martin,
I see you've pinned Django to version 1.11 (`Django~=1.11`). Is there some specific reason behind this? 

I'm using Django 2.1 + Pipenv currently and since commit https://github.com/weinbusch/django-tex/commit/d99038c26acf8fc13569e463d6e75fd3b0e27711 pipenv will install Django 1.11.x as a dependency of django-tex which my project doesn't support anymore...

Cheers and thanks,
Max

**Comment by weinbusch** [comment]
Thanks for noting. There wasn't a particular reason. I fixed it and hope it works. Please let me know otherwise.

**Comment by gegenschall** [comment]
Works! Thanks a bunch! :)
