### ISSUE TITLE
Tex template producing "Encountered unknown tag 'graphicspath'." error

### ISSUE THREAD

**Issue by Monsterhulk** [weinbusch/django-tex#9]
At first many thanx for this library. As i am new to python and django this package was my way to go to get a fast way to generate *.pdf files. But now i encountered above mentioned error.

I am using the latest version of django and python. I am developing on Windows10.

I tried to use the LATEX_GRAPHICSPATH like you mentioned in your brief documentation. 

My settings.py
`LATEX_INTERPRETER = 'lualatex'
LATEX_GRAPHICSPATH = ['C:\\Users\\dm\\Projects\\djangoprojects\\doctheur\\doctheur\\jinja2\\img',]

TEMPLATES = [
    {
        'NAME': 'tex',
        'BACKEND': 'django_tex.engine.TeXEngine', 
        'APP_DIRS': True,
        'DIRS': ['%s/jinja2/'% (PROJECT_DIR),],        
    },
`

My "Tex Template (Namenlos-3.tex)"
`\usepackage{graphicx} 
{% graphicspath %}`

Everything else is working fine. And if i hardcode the paths to the graphics the \includegraphics worx fine either. 

What am i doing wrong? 

Another thing i cannot get to work is loading some .ttf - fonts from a custom folder. 

Sorry for my dumb questions, but i didn t know where i should place them and google wasn t a big help.

Regards Möbius

**Comment by weinbusch** [comment]
Which versions of django-tex and jinja are you using? The `{% graphicspath %}` tag is only available in django-tex >= 1.1.5.

**Comment by Monsterhulk** [comment]
I ve downloaded django-tex, django, python and jinja  at the 3th of june or later ... i cannot tell the exact version cause i am not at my working station now, but i think it should be the latest version.

**Comment by weinbusch** [comment]
Version 1.1.5 was published on June 6. So you might just have missed the update. Please try updating to solve your problem.

Regarding the .ttf fonts, I need more info to help you. But I am not an expert when it comes to custom fonts in latex...

**Comment by Monsterhulk** [comment]
Hi Martin and thank you very much for your fast responses. I realy appreciate After i ve upgraded to the latest version (1.1.6) of your package the `{% graphicspath %}` is now recognized. The problem is now, that it seems not to get rid of the quotation marks `cannot find image file '"c:/Users/dm/Proj
ects/djangoprojects/doctheur/doctheur/jinja2/img/"buli-logo_80x80.png'` ... have i done something wrong? Latex seems to "think" the quotation-marks are part of the path. 

For the .ttf fonts i will try some other methods. But i think as you described your package uses a temp folder, the .ttf fonts will have the same problem like the graphics.

Best regards Möbius

**Comment by Monsterhulk** [comment]
Hi Martin, 

think i ve found something that helps with my problem. In your extensions.py you concatenated the string like this `path = '{"' + path + '"}'` ... latex's \graphicpath works with no double quotes around the paths. To fix it i ve turned your statement into `path = '{' + path + '}'` ... this works fine for lualatex. But i haven t looked if it works for pdflatex etc ...

Best regards Möbius

**Comment by weinbusch** [comment]
The double quotes were added to support graphics paths having whitespaces. This works for pdflatex but not for lualatex. I couldn't find a better way of supporting paths with whitespaces. \usepackage{grfffile} is an option for pdflatex but also fails in case of lualatex.

Therefore, I will modify `extensions.py` to include double quotes only, if pdflatex is used (and if the path actually contains whitespaces).

For the time being, a workaround for you could be to hardcode the \graphicspath command in your templates withouth relying on the template tag.
